# -*- coding: utf-8 -*-
"""q1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U86pmF0k-QCDg0Tn6G90CnWMrMmsyu3P
"""

def minimum(arr):
    """
    Finds the minimum element in an array.

    Args:
        arr: A list of integers.

    Returns:
        The minimum element in the array.
    """
    n = len(arr)
    if(n==0):
        return None
    min_val = arr[0]
    for i in range(1,len(arr)):
        if(min_val > arr[i]):
            min_val = arr[i]
    return min_val
    

# Test
array = [4, 7, 1, 3, 9, 1]
print("minimum element:", minimum(array))