# -*- coding: utf-8 -*-
"""q2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RXViHTatWMii_SK8siow7Ja432a4rzN-
"""

def second_minimum(arr):
    
    n = len(arr)
    if(n == 0 or n == 1):
        return None
    min_1 = None
    min_2 = None
    for i in range(0,len(arr)):
        if(min_1 == None or arr[i] < min_1):
            min_2 = min_1
            min_1 = arr[i]
            
        elif((min_2 == None or arr[i] < min_2) and arr[i] > min_1 ):
            min_2 = arr[i]
    return min_2
# Test
array = [4,3,8,9,9,9,9,1,1,1,1,2,2,2,4,5,6,7,8,2,2,34,5,2]
print("Second minimum element:", second_minimum(array))