# -*- coding: utf-8 -*-
"""q4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CrDn8VVkK8GSE0ppLeQuQs5EMDqiUkqL
"""

# Node class to represent each node in the binary tree
class Node:
    def __init__(self, value):
        self.value = value
        self.left = None
        self.right = None

# Implement this function to read the tree structure from a file
def parse_tree(file_path):
    with open(r"C:\Users\saikiran\OneDrive\Desktop\Sem 3\DSA\Mid\tree.txt" , "r") as f:
        lines = f.readlines()
        n = int(lines[0])
        dic_left = {}
        dic_right = {}
        for i in range(1,len(lines)):
            node , parent , left , right = lines[i].split(" ")
            node = int(node)
            dic_left[node] = int(left)
            dic_right[node] = int(right)
        def helper(node):
            if(node == 0):
                return None
            root = Node(node)
            if node in dic_left:
                root.left = helper(dic_left[node])
            if node in dic_right:
                root.right = helper(dic_right[node])
            return root
        return helper(1)

    """
    Parse the binary tree structure from a file and build it using lists.

    :param file_path: The path to the file containing the binary tree structure
    :return: The root node of the binary tree
    """
    # TODO

# Implement this function to recursively swap the left and right children
def swap_children(node):
    if(node == None):
        return None
    node.left , node.right = node.right , node.left
    swap_children(node.left)
    swap_children(node.right) 
    """
    Recursively swap the left and right children of every node in the tree.

    :param node: The current node being processed
    """


# Helper function for pre-order traversal to verify the tree structure
def pre_order_traversal(node):
   if node == None:
       return 
   print(node.value)
   pre_order_traversal(node.left)
   pre_order_traversal(node.right)
   """
   implement the pre-order traversal to verify the tree structure
   :param node: The current node being processed
   """



# Main function to run the lab
if __name__ == "__main__":
    # Parse the binary tree from a text file (replace 'tree.txt' with your file path)
    root = parse_tree(r'C:\Users\saikiran\OneDrive\Desktop\Sem 3\DSA\Mid\tree.txt')

    print("Original tree pre-order traversal:")
    pre_order_traversal(root)
    print()

    # Swap the children
    swap_children(root)

    print("Tree after swapping children pre-order traversal:")
    pre_order_traversal(root)
    print()